# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94fef3ce297a559d0bed380f3024bbdd93ebc3c8cdc817ae0de89ad146747c5fa2b30781e9d4fa46f2edf8ed3e40efe2f517e5f4b501dd6d1a2c5b43111df94d

test:
  secret_key_base: 0c2d0d48d2e715087226e2331c2c62ed946db6c53a47553f662788620b982ed8ea839f7671734d77b92dc66c1310e1f1c55bb92b44524d7038fba724f43648cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
